sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: q3V/PX8XsReEaDGtQcKf+2m4Qf+oh1zhOMDVvZW0Xv9LMQ5gSbNDqPgocqBL1Je4A9ybEPctZmZW6eH1fGEUWtTJneOORnwvNWquQXapn2R8fMg8/qC66VMMh3YIrgF82JwnGhwDzTQERlTjBmjFpiy+E6F3MD11p0jDoVe7amGPoKR5VcwaHuofR/EGX8ddabyM40toaSXXoUuuRkaK2pSuuoMGy2uydIJRvhtFlycmb2xIhlR+6D2xuAM8281fXYmWc+AfWc8hKvfp6+Qiow/+mU5KAkid1j0Z4EVfC6OMCK46yj/r3XsiLNbAoFRUT5Medybvy5a+l8tvig0JdBgOf52C4xWVBLikovPaWupbr+cQ0LupEcRdJxNZEs8AYbeoQh2ADBYMPIA2ooQLvyhXL/Kng4C4NMc+opuqxCSx8kEckcvWJ5zgti27nNRB1Y2DYtPhaOoU/P4HJdeUj8WEcjKEyFU7QnatAqE9svsh1Q1n034AgdaoI9+qS7hhC1g5BpYHbzmit2Own3YD9NM8LKcomnzXAg3o9flVXVfuKBYA4FeZ5S7o/OB7cXFF5XzB24U2WNjJccbaQnpnOVhQ8+yLmuOUScNU2vdLXfIgehJzFpX6rMqEbAvH29wyhmze5Bjdzlq9x9a0AMlS4Ilk3sGGMoC0D3ATxbKoKxg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Little-Wars--a-game-for-boys-from-twelve-years-of-age-to-one-hundred-and-fifty-and-for-that-mo__3691
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy